steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/website/website:$COMMIT_SHA'
      - '-t'
      - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/website/website:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/website/website:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/website/website:latest'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'website'
      - '--image'
      - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/website/website:$COMMIT_SHA'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'
      - '--port'
      - '8080'
      - '--allow-unauthenticated'
      - '--memory'
      - '256Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '3'

images:
  - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/website/website:$COMMIT_SHA'
  - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/website/website:latest'

options:
  logging: CLOUD_LOGGING_ONLY
